# Site settings

title: Things I Feel Like Talking About
description: "I'm learning Ruby/Rails. I'm also learning html, CSS, and some js, plus anything else that catches my eye in the process. In the Fall of 2017, I'll be attending The Turing School to get some formal training in what the hell I'm doing, but till then, I'm shooting in the dark. This site is my first attempt at making something that wasn't from a point and click site generator, and it will be changing frequently as I learn new things. It's a Jekyll site now, but the goal is to rebuild it in Rails at some point."

url: 'http://mrpants.io'
baseurl: '/'
google_analytics: 'UA-89828330-1'
disqus_shortname: 'mrpants-io-4'

author:
  name: 'Aram Anderson'
  email: aram.j.anderson@gmail.com
  twitter_username: aram987
  github_username:  mr-pants

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
